# The base URL of the eKOL-TNV service
# (excluding any session identifiers etc.)
url: https://www.wg-gesucht.de

town: Potsdam
type: WG-Zimmer

# include offers from the last x minutes (only goes up to 60 minutes)
minutes: 15
